### ISSUE TITLE
Autoload external $ref files

### ISSUE THREAD

**Issue by PanosBougas** [karenetheridge/OpenAPI-Modern#51]
Hello again,

Considering the following openapi schema
```yaml
openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Sample API"
  description: Buy or rent spacecrafts
  license:
    name: Apache 2.0
paths:
  /spacecraft/{id}:
    parameters:
      - $ref: components/parameters/path/id.yaml
    get:
      summary: Read a spacecraft
      operationId: getResourceById
      responses:
        "200":
          description: The spacecraft corresponding to the provided `id`
          content:
            application/json:
              schema:
                $ref: components/schemas/spacecraft.yml
```

This passes compilation but when trying to call `validate_request` inside the controller module
```perl
$controller->openapi->validate_request( $controller->req );
```
 I get this:
```
$VAR1 = 'EXCEPTION: unable to find resource /<full_path>/components/parameters/path/id.yaml';
```

Is this a bug?
or
Do I need to do [this](https://metacpan.org/pod/JSON::Schema::Modern#add_schema) in order to add external files in general?

```perl
$controller->openapi->evaluator->add_schema('/spacecraft/{id}' => 'components/schemas/spacecraft.yml');
```

**Comment by PanosBougas** [comment]
So there is not way for me to have multiple files and let the OpenAPI module resolve file references and add them to the final OpenAPI object. This way I will have to write one huge file that will be quite difficult to manage if I want to avoid messing with the JSON::Schema::Modern::Document::OpenAPI object .

I was hoping for such a thing since another openapi [module](https://metacpan.org/dist/Mojolicious-Plugin-OpenAPI/view/lib/Mojolicious/Plugin/OpenAPI/Guides/OpenAPIv3.pod#References-with-files) does it. Unfortunately I can't use that either since I am forced to define my routes inside the `x-mojo-to` object.

**Comment by karenetheridge** [comment]
Yes, you can have multiple files, where references to them are resolved at runtime. However they are not loaded from disk or the network automatically - you need to add those documents yourself in advance.

You would do that with:

```
my $js = JSON::Schema::Modern->new(...);
my $document = JSON::Schema::Modern::Document::OpenAPI->new(
  ... follow the example in the SYNOPSIS, loading your schema data from disk and declaring the correct uri
);
$js->add_schema($document);  # see the docs
# .. create document and add it for every external file you have

my $openapi = OpenAPI::Modern->new(
  ...,
  evaluator => $js,
);
```

**Comment by PanosBougas** [comment]
ok I see, perhaps I could create a new mojo plug in that loads and builds the `$openapi` object you described, based on the files that I need. 

Considering that I have such an object at hand, do I need to make changes to the `$ref` values I defined in my first comment? I am assuming that it will behave as a single OpenAPI Schema file now, correct?

**Comment by karenetheridge** [comment]
The `$ref`s need to be resolvable, using standard URI resolution rules -- this is a JSON Schema thing, not OpenAPI. The resolved URIs should match up with whatever identifiers you provided when you called `add_schema`, or `$id` keywords in the schemas themselves.

> perhaps I could create a new mojo plug in that loads and builds the $openapi object you described, based on the files that I need

Perhaps. This could potentially be a feature of the existing plugin, e.g. a directory name to load all files from, but I haven't had need for that myself yet.

**Comment by PanosBougas** [comment]
ok this is clear for me now, thanks! I will try to use it this way for now until this feature becomes available.

Regarding this new feature. 
Wouldn't be better if instead of providing a `schema_dir` we provided just the OpenAPI file path as we currently do, then the module reads it and goes through it, for each `$ref` that it finds, it tries to resolve them based on their "path" values.
For example if we have such a  `$ref: "components/parameters/resourceId"` 

The module could try to resolve it through the components section of the OpenAPI file 
or if that fails
Could use the path as a relative path to resolve it through disk and load it to the evaluator object automatically.

**Comment by PanosBougas** [comment]
I implemented a plug in based on the `Mojolicious::Plugin::OpenAPI::Modern`. Could be a potential PR but it's a bit rough around the edges currently. But it works the way you described, which is great! 

It does not work for OpenAPI components though. I get this:
```missing property: openapi```
This is my component file
```yaml
name: id
description: The unique identifier of the resource
in: path
required: true
schema:
  type: string
  pattern: '^[1-9]\d*$'
```

I believe this happens because this is not `JSON::Schema::Modern::Document::OpenAPI` object in all its glory but an OpenAPI component. 
I can't use the `JSON::Schema::Modern::Document` either cause this is not a JSON Schema thing. I get:
```'/required': required value is not an array```
Is there a way to make that work as well somehow?

By the way this is part of my code that loads each file.
```perl

sub _load_schemas {
    my ( $jsm, $file_paths ) = @_;

    for my $file_path (@$file_paths) {
        my $schema = _load_schema($file_path); #decoded json schema
        my $document;
        if ( $file_path =~ /schemas/ ) { # the if is dumb for now
            $document = JSON::Schema::Modern::Document->new(
                canonical_uri => "file://" . $file_path,
                evaluator     => $jsm,
                schema        => $schema,
            );
        }
        else {
            $document = JSON::Schema::Modern::Document::OpenAPI->new(
                canonical_uri => "file://" . $file_path,
                evaluator     => $jsm,
                schema        => $schema,
            );
        }
        $jsm->add_schema( $file_path => $document );
    }

}
```
