### ISSUE TITLE
Support Plack::Request

### ISSUE THREAD

**Issue by fabzzap** [karenetheridge/OpenAPI-Modern#67]
Nowadays OpenAPI::Modern
> Validates an [HTTP::Request](https://metacpan.org/pod/HTTP::Request) or [Mojo::Message::Request](https://metacpan.org/pod/Mojo::Message::Request) object

Those who use Plack, however, need to jump through some loops. It would be great if OpenAPI::Modern was also able to validate Plack::Request objects

**Comment by karenetheridge** [comment]
Interesting.

It looks like conversion is pretty straightforward: `Mojo::Message::Request->new->parse($plack_request->env)`.

**Comment by karenetheridge** [comment]
done in version 0.052.
