### ISSUE TITLE
Catalyst::Request, ::Response support

### ISSUE THREAD

**Issue by fleetfootmike** [karenetheridge/OpenAPI-Modern#75]
see https://github.com/fleetfootmike/OpenAPI-Modern/pull/1/files for a working attempt - feel free to abuse as needed :D

All tests pass.

**Comment by fleetfootmike** [comment]
...ish. here be dragons - Catalyst::Request glomps the request body into an HTTP::Body object, and getting the raw data back out of that is eluding me at present.

**Comment by fleetfootmike** [comment]
pull request (see first comment) updated to something that actually works.

**Comment by karenetheridge** [comment]
done in release 0.064!
